# Generated by Django 5.2.16 on 2026-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Trip", "On Trip"),
                    ("Off Duty", "Off Duty"),
                    ("Suspended", "Suspended"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Dispatched", "Dispatched"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Trip", "On Trip"),
                    ("In Shop", "In Shop"),
                    ("Retired", "Retired"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
