# Generated by Django 5.2.16 on 2026-07-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_driver_status_alter_trip_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150)),
                ("otp", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Trip", "On Trip"),
                    ("Off Duty", "Off Duty"),
                    ("Suspended", "Suspended"),
                    ("available", "Available"),
                    ("on-trip", "On Trip"),
                    ("off-duty", "Off Duty"),
                    ("suspended", "Suspended"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Dispatched", "Dispatched"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("scheduled", "Scheduled"),
                    ("in-progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Trip", "On Trip"),
                    ("In Shop", "In Shop"),
                    ("Retired", "Retired"),
                    ("idle", "Available"),
                    ("active", "On Trip"),
                    ("maintenance", "In Shop"),
                    ("retired", "Retired"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
