# Generated by Django 5.2.16 on 2026-07-12 08:52

from django.db import migrations, models

def normalize_statuses(apps, schema_editor):
    Vehicle = apps.get_model('api', 'Vehicle')
    Driver = apps.get_model('api', 'Driver')
    Trip = apps.get_model('api', 'Trip')

    # Vehicle mapping:
    # idle -> Available, active -> On Trip, maintenance -> In Shop, retired -> Retired
    for v in Vehicle.objects.all():
        if v.status == 'idle':
            v.status = 'Available'
        elif v.status == 'active':
            v.status = 'On Trip'
        elif v.status == 'maintenance':
            v.status = 'In Shop'
        elif v.status == 'retired':
            v.status = 'Retired'
        v.save()

    # Driver mapping:
    # available -> Available, on-trip -> On Trip, off-duty -> Off Duty, suspended -> Suspended
    for d in Driver.objects.all():
        if d.status == 'available':
            d.status = 'Available'
        elif d.status == 'on-trip':
            d.status = 'On Trip'
        elif d.status == 'off-duty':
            d.status = 'Off Duty'
        elif d.status == 'suspended':
            d.status = 'Suspended'
        d.save()

    # Trip mapping:
    # scheduled -> Draft, in-progress -> Dispatched, completed -> Completed, cancelled -> Cancelled
    for t in Trip.objects.all():
        if t.status == 'scheduled':
            t.status = 'Draft'
        elif t.status == 'in-progress':
            t.status = 'Dispatched'
        elif t.status == 'completed':
            t.status = 'Completed'
        elif t.status == 'cancelled':
            t.status = 'Cancelled'
        t.save()

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_otpstore_alter_driver_status_alter_trip_status_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_statuses),
        migrations.AlterField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Trip", "On Trip"),
                    ("Off Duty", "Off Duty"),
                    ("Suspended", "Suspended"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Dispatched", "Dispatched"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Trip", "On Trip"),
                    ("In Shop", "In Shop"),
                    ("Retired", "Retired"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
