# Generated by Django 5.2.16 on 2026-07-12 08:59

import django.db.models.deletion
from django.db import migrations, models

def clear_tables_before_alter(apps, schema_editor):
    Trip = apps.get_model('api', 'Trip')
    Maintenance = apps.get_model('api', 'Maintenance')
    FuelLog = apps.get_model('api', 'FuelLog')
    Expense = apps.get_model('api', 'Expense')
    
    Trip.objects.all().delete()
    Maintenance.objects.all().delete()
    FuelLog.objects.all().delete()
    Expense.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_driver_status_alter_trip_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="region",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.RunPython(clear_tables_before_alter),
        migrations.AlterField(
            model_name="expense",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="api.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="fuellog",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fuel_logs",
                to="api.driver",
            ),
        ),
        migrations.AlterField(
            model_name="fuellog",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fuel_logs",
                to="api.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenances",
                to="api.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_trips",
                to="api.driver",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="api.vehicle",
            ),
        ),
    ]
