# Generated by Django 5.2.16 on 2026-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_vehicle_region_alter_expense_vehicle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("driver", "Driver"),
                    ("safety", "Safety Officer"),
                    ("finance", "Financial Analyst"),
                    ("admin", "System Administrator"),
                ],
                default="manager",
                max_length=20,
            ),
        ),
    ]
